# Generated by Django 4.2.6 on 2024-06-05 22:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo_path', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('video_path', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=55)),
                ('lastName', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile_picture_path', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='kinect_core.user')),
                ('userID_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='kinect_core.user')),
            ],
        ),
        migrations.CreateModel(
            name='reel_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.reel')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.user')),
            ],
        ),
        migrations.AddField(
            model_name='reel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.user'),
        ),
        migrations.CreateModel(
            name='photo_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.photo')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.user')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.user'),
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('userReceiverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_message', to='kinect_core.user')),
                ('userSenderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to='kinect_core.user')),
            ],
        ),
        migrations.CreateModel(
            name='comment_for_reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.reel')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.user')),
            ],
        ),
        migrations.CreateModel(
            name='comment_for_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.photo')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.user')),
            ],
        ),
    ]
