# Generated by Django 4.2.6 on 2024-06-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinect_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentForReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment_for_reel',
            name='reelID',
        ),
        migrations.RemoveField(
            model_name='comment_for_reel',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='photo_like',
            name='photoID',
        ),
        migrations.RemoveField(
            model_name='photo_like',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='reel_like',
            name='reelID',
        ),
        migrations.RemoveField(
            model_name='reel_like',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='user_following',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='user_following',
            name='userID_following',
        ),
        migrations.RenameField(
            model_name='reel',
            old_name='userID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='comment_for_photo',
        ),
        migrations.DeleteModel(
            name='comment_for_reel',
        ),
        migrations.DeleteModel(
            name='photo_like',
        ),
        migrations.DeleteModel(
            name='reel_like',
        ),
        migrations.DeleteModel(
            name='user_following',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='kinect_core.user'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='user_id_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='kinect_core.user'),
        ),
        migrations.AddField(
            model_name='reellike',
            name='reel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.reel'),
        ),
        migrations.AddField(
            model_name='reellike',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.user'),
        ),
        migrations.AddField(
            model_name='photolike',
            name='photo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.photo'),
        ),
        migrations.AddField(
            model_name='photolike',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.user'),
        ),
        migrations.AddField(
            model_name='commentforreel',
            name='reel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.reel'),
        ),
        migrations.AddField(
            model_name='commentforreel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.user'),
        ),
        migrations.AddField(
            model_name='commentforphoto',
            name='photo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.photo'),
        ),
        migrations.AddField(
            model_name='commentforphoto',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinect_core.user'),
        ),
    ]
