# Generated by Django 4.2.6 on 2024-06-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinect_core', '0002_commentforphoto_commentforreel_photolike_reellike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='user_id_followers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='kinect_core.user'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='user_id_following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='kinect_core.user'),
        ),
    ]
