# Generated by Django 4.2.6 on 2024-06-09 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinect_core', '0003_remove_userfollowing_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id_followers',
            new_name='user_followed',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id_following',
            new_name='user_following',
        ),
        migrations.AlterField(
            model_name='message',
            name='userReceiverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='kinect_core.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='userSenderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='kinect_core.user'),
        ),
    ]
