# Generated by Django 4.2.6 on 2024-06-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinect_core', '0004_rename_user_id_followers_userfollowing_user_followed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='userReceiverID',
            new_name='user_receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='userSenderID',
            new_name='user_sender',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_path',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='video_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_path',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(null=True, upload_to='posts/images'),
        ),
        migrations.AddField(
            model_name='reel',
            name='video',
            field=models.FileField(null=True, upload_to='posts/videos'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
