# Generated by Django 4.2.6 on 2024-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinect_core', '0006_alter_commentforphoto_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='photo_path',
        ),
        migrations.AddField(
            model_name='commentforphoto',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
