# Generated by Django 4.2.6 on 2024-07-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinect_core', '0007_rename_photo_photo_photo_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_path',
            new_name='photo',
        ),
    ]
