# Generated by Django 4.2.6 on 2024-07-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinect_core', '0010_remove_photo_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_path',
            field=models.ImageField(null=True, upload_to='posts/images'),
        ),
    ]
